services:
  redis:
    image: redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=api
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - database
    environment:
      - DB_NAME=api
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=database
      - DB_PORT=3306

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - DATADIR=appdata

    env_file:
      - .env
